export function createAppId(): string {
  return crypto.randomUUID();
}

export {
  CircularDependencyError,
  createServiceContainer,
  createToken,
  ServiceAlreadyRegisteredError,
  ServiceContainer,
  ServiceNotRegisteredError,
  type ServiceFactory,
  type ServiceToken,
} from './di';
export {
  inspectVideoFileRequestSchema,
  openRecentVideoRequestSchema,
  recentVideoFileResponseSchema,
  VIDEO_IPC_CHANNELS,
  videoImportErrorResponseSchema,
  videoImportResultSchema,
  videoMetadataResponseSchema,
  type InspectVideoFileRequest,
  type OpenRecentVideoRequest,
  type RecentVideoFileResponse,
  type VideoImportErrorResponse,
  type VideoImportResult,
  type VideoIpcChannel,
  type VideoMetadataResponse,
  type DubForgeApi,
  type DubForgeFilesApi,
  type DubForgePipelineApi,
  type DubForgeVideoApi,
  PIPELINE_IPC_CHANNELS,
  cancelPipelineJobRequestSchema,
  pipelineEventSchema,
  pipelineJobResponseSchema,
  startPipelineJobRequestSchema,
  type CancelPipelineJobRequest,
  type PipelineEventPayload,
  type PipelineIpcChannel,
  type PipelineJobResponse,
  type StartPipelineJobRequest,
  MODEL_IPC_CHANNELS,
  modelCategorySchema,
  modelIdRequestSchema,
  modelResponseSchema,
  modelStatusSchema,
  modelsChangedEventSchema,
  verificationCheckStepSchema,
  verificationReportSchema,
  downloadReportSchema,
  assetDiagnosticsResponseSchema,
  verifyModelResponseSchema,
  type ModelIdRequest,
  type ModelIpcChannel,
  type ModelResponse,
  type ModelsChangedEvent,
  type VerificationCheckStepResponse,
  type VerificationReportResponse,
  type DownloadReportResponse,
  type AssetDiagnosticsResponse,
  type VerifyModelResponse,
  type DubForgeModelsApi,
} from './ipc';
export {
  calculateThumbnailTimestampSeconds,
  createValidationFailure,
  createFfprobeValidationFailure,
  buildFfprobeArgs,
  ffprobeOutputSchema,
  FfprobeExecutionError,
  FfprobeParseError,
  formatFfprobeDiagnostics,
  type FfprobeDiagnostics,
  MAX_RECENT_VIDEO_FILES,
  MAX_VIDEO_DURATION_SECONDS,
  MAX_VIDEO_FILE_SIZE_BYTES,
  parseFfprobeOutput,
  SUPPORTED_VIDEO_EXTENSIONS,
  THUMBNAIL_HEIGHT,
  THUMBNAIL_POSITION_RATIO,
  THUMBNAIL_WIDTH,
  toVideoMetadata,
  validateVideoExtension,
  validateVideoFileStats,
  validateVideoProbe,
  type CachedVideoRecord,
  type FfprobeOutput,
  type VideoFileStats,
  type VideoProbeResult,
  type VideoValidationCode,
  type VideoValidationFailure,
  VideoValidationException,
} from './video';
